[env:stm32f411e_disco]
platform = ststm32
board = genericSTM32F411RE
framework = arduino

board_build.mcu = stm32f411vet6
board_build.variant = STM32F4xx/F411V(C-E)T

build_flags = 
    -D ARDUINO_GENERIC_F411VETX
    -D STM32F411xE
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON

monitor_speed = 115200
upload_protocol = stlink

lib_deps = 
    https://github.com/simplefoc/Arduino-FOC.git#dev